spring:
  datasource:
    url: ${POSTGRESQL_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    parameters:
      searchPath: classpath:db/changelog/